### ISSUE TITLE
research possible cross-platform serif fonts for headers and body

### ISSUE THREAD

**Issue by waldyrious** [waldyrious/downstyler#15]

**Comment by waldyrious** [comment]
For headers ([wide serif](http://code.stephenmorley.org/html-and-css/the-myth-of-web-safe-fonts/)), the best approach is to use `font-family: Georgia, Century Schoolbook L, serif`. Georgia is almost universally supported on Mac and Windows,<sup>[1]</sup> and on Linux where it isn't available, Century Schoolbok L is the closest, reasonably available<sup>[2]</sup> approximation. Compare:

Georgia:
![georgia](https://cloud.githubusercontent.com/assets/478237/17385158/c4591d6e-59d8-11e6-94ec-ec5b94ca072a.png)

Century Schoolbook L:
![century-schoolbook-l](https://cloud.githubusercontent.com/assets/478237/17385160/cb2515f8-59d8-11e6-893f-854b5f0d8550.png)

----
1. http://www.cssfontstack.com/Georgia
2. http://fontfamily.io/Georgia,Century_Schoolbook_L

**Comment by waldyrious** [comment]
For body text, further investigation is needed to find cross-platform equivalents, but it appears that the default is acceptable given proper line-height, so I'll just style the headers.

**Comment by waldyrious** [comment]
Note: this topic was further explored in #25.

**Comment by waldyrious** [comment]
Obs: just came across http://wcm1.web.rice.edu/mutt-tips.html, which reads quite nicely. I might explore using Georgia as the default font instead of Palatino.

Here is what the page looks like after unstyle + using both fonts (Palatino on left, Georgia on right -- click the images for the full size version):

<img width="300" alt="screen shot 2017-04-26 at 00 18 10" src="https://cloud.githubusercontent.com/assets/478237/25411683/0d01d25a-2a16-11e7-8396-137cd77aa3f8.png"> <img width="300" alt="screen shot 2017-04-26 at 00 18 29" src="https://cloud.githubusercontent.com/assets/478237/25411687/10580032-2a16-11e7-9db7-652d3c425fd5.png">

**Comment by waldyrious** [comment]
Some more options:

| Merriweather | Symbola |
| :---: | :---: |
| ![font-merriweather](https://user-images.githubusercontent.com/478237/34640547-4428e8d2-f2ec-11e7-818a-6cc5245bb9af.png) | ![font-symbola](https://user-images.githubusercontent.com/478237/34640549-4ee87a12-f2ec-11e7-95a3-1eb8acb7c4a7.png) |
| **Gentium** | **Linux Libertine** |
| ![font-gentium](https://user-images.githubusercontent.com/478237/34640553-5b150526-f2ec-11e7-80aa-52be52d1bb0c.png) | ![font-libertine](https://user-images.githubusercontent.com/478237/34640556-60462700-f2ec-11e7-9ac2-a44d8f776531.png) |
| **STIX** | |
| ![font-stix](https://user-images.githubusercontent.com/478237/34640559-6c2e02a4-f2ec-11e7-9f81-de5fda1e8972.png) | |

**Comment by waldyrious** [comment]
(As a quick note, both Linux Libertine and STIX seem to be quite nice as generic serif fonts. It might be worth looking for similarities on Windows and macOS and consider changing the default, since Palatino is quite wide, and a little bit opinionated)

**Comment by codygarver** [comment]
This issue belongs instead to https://github.com/elementary/fonts

**Comment by codygarver** [comment]
Sorry, that comment was actually meant for elementary/seed-metapackages#5

**Comment by waldyrious** [comment]
No problem, @codygarver. Please thumbs-up this comment if you're ok with me deleting yours above to keep the thread clean.

**Comment by waldyrious** [comment]
[Repology provides a list](https://repology.org/metapackage/fonts:linuxlibertine/versions) of the distro repositories where the Linux Libertine package is *available* (but not necessarily installed by default -- that information should eventually be compiled at [unix-manifests](https://github.com/waldyrious/unix-manifests) or some similar project... maybe a nice candidate for a Wikidata import?)

**Comment by waldyrious** [comment]
Reopening to reflect the undecided status per the last few comments.
