### ISSUE TITLE
XML error at http://waldyrious.net/downstyler/ in Firefox

### ISSUE THREAD

**Issue by hartwork** [waldyrious/downstyler#62]
```
XML Parsing Error: not well-formed
Location: http://waldyrious.net/downstyler/
Line Number 86, Column 74:
            '&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot href=&quot;'+
-------------------------------------------------------------------------^
```

Also, an SSL redirect would be great.

Thank you!

**Comment by waldyrious** [comment]
Thanks for reporting this! I'll fix it in a moment.

As for the SSL redirect, I have just turned it on in the repository settings:

![Screenshot 2021-05-04 at 19 20 52](https://user-images.githubusercontent.com/478237/117051007-f619d400-ad0d-11eb-94b4-37b6bf986aad.png)

Thanks for the heads-up!

**Comment by hartwork** [comment]
Awesome, thank you! :+1:
